// Code generated by goctl. DO NOT EDIT.
package types

type GetSchemasRequest struct {
}

type GetSchemasResponse struct {
	Names []string `json:"names"`
}

type HealthResponse struct {
	Message string `json:"message"`
}

type VersionResponse struct {
	Version string `json:"version"`
}
