### GET Version
GET http://{{rest}}/version

### GET Health
GET http://{{rest}}/health

### POST UP
POST http://{{rest}}/up
Content-Type: application/json

{
  "ds": "mysql",
  "schema": "hello1",
  "version": 1
}
