// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dsvm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 获取Schema名称
				Method:  http.MethodGet,
				Path:    "/get/schemas",
				Handler: GetSchemasHandler(serverCtx),
			},
			{
				// 健康检查
				Method:  http.MethodGet,
				Path:    "/health",
				Handler: HealthHandler(serverCtx),
			},
			{
				// APP 版本
				Method:  http.MethodGet,
				Path:    "/version",
				Handler: VersionHandler(serverCtx),
			},
		},
	)
}
