// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"dsvm/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				// 需要初始化的Schema名称
				Method:  http.MethodGet,
				Path:    "/init/schemas",
				Handler: InitSchemasHandler(serverCtx),
			},
		},
	)
}
