Name: dsvm
Version: 1.1.1

RestServerConf:
  Name: dsvm-rest-server
  Host: 0.0.0.0
  Port: 8081

RpcServerConf:
  Name: dsvm-rpc-server
  ListenOn: 0.0.0.0:8080

DemoClientConf:
  Target: 127.0.0.1:8080

LogxConf:
  # debug,info,error,severe
  Level: info
  KeepDays: 15
